# sonar-project.properties (à la racine du projet)
sonar.projectKey=jenkins-CI-CD-pipeline-sonarQube
sonar.projectName=jenkins-CI-CD-pipeline-sonarQube
sonar.host.url=http://localhost:9000
sonar.login=sqp_4b4782a0b55bd4ddd404971c0222aed8e186dcdc
sonar.sources=src
sonar.exclusions=node_modules/**,coverage/**